name: test

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.26"
          - "1.25"
          - "1.24"
          - "1.23"
          - "1.22"
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
          - "1.17"

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "${{ matrix.go }}"
      - run: go test -v -coverprofile=profile.cov ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: shogo82148/pointer
          files: profile.cov
          flags: go-${{ matrix.go }}
